// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpzcogoixzxlzaaijdcr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwemNvZ29peHp4bHphYWlqZGNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE0NjE0OTIsImV4cCI6MjA4NzAzNzQ5Mn0.NaRvExqgGP3hvdN-Dw4hscjsV4QT0D04K8aMVYVINyA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});